config/urls.py
from django.contrib import admin
from django.urls import include, path
from accounts import views
from accounts.forms import EmailAuthenticationForm
from django.contrib.auth.views import LoginView

app_name = 'upload_qpj'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizzes.urls')),
    path('quizzes/', include('quizzes.urls')),
    path('login/', LoginView.as_view(form_class=EmailAuthenticationForm,
                                     template_name='registration/index.html'), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('accounts/', views.UserCreate.as_view(), name='user_create'),
    path('accounts/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('accounts/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('accounts/password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('accounts/password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('accounts/password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('sysconfig/', include('system_conf.urls')),
]

quizzes/urls.py
from django.urls import path

from . import views

app_name = 'quizzes'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('quizzes/', views.make_question, name='make_question'),
]

accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a user with the given username, email, and
        password."""
        if not email:
            raise ValueError('emailは必須項目です。')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm
)
from django.contrib.auth import authenticate, get_user_model
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class EmailAuthenticationForm(forms.Form):
    email = forms.EmailField(max_length=254,
                             widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(label=_("Password"), strip=False,
                               widget=forms.PasswordInput)
    error_messages = {
        'invalid_login': "Eメールアドレス または パスワードに誤りがあります。",
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        # Set the label for the "email" field.
        self.email_field = User._meta.get_field("email")
        if self.fields['email'].label is None:
            self.fields['email'].label = capfirst(self.email_field.verbose_name)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'email': self.email_field.verbose_name})
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(self.error_messages['inactive'], code='inactive')

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('email', "password1", "password2",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.contrib.auth.views import (
    LogoutView
)
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect
from django.template.loader import get_template
from django.views import generic
from .forms import (UserCreateForm)
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.mixins import LoginRequiredMixin

User = get_user_model()


class EmailAuthBackend(ModelBackend):
    """ログインページ"""
    def authenticate(self, request, email=None, password=None, **credentials):
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            return None
        else:
            if user.check_password(password) and self.user_can_authenticate(user):
                return user


class Logout(LogoutView):
    """ログアウトページ"""
    template_name = "registration/index.html"


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'accounts/register.html'
    form_class = UserCreateForm

    def form_valid(self, form):

        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('accounts/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('accounts/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        return redirect('user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録"""
    template_name = 'accounts/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'accounts/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60 * 60 * 24)  # 1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoenNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class PasswordChange(LoginRequiredMixin, PasswordChangeView):
    """パスワード変更ビュー"""
    success_url = reverse_lazy('password_change_done')
    template_name = 'accounts/password_change.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # 継承元のメソッドCALL
        context["form_name"] = "password_change"
        return context


class PasswordChangeDone(LoginRequiredMixin, PasswordChangeDoneView):
    """パスワード変更完了"""
    template_name = 'accounts/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'accounts/mail_template/reset/subject.txt'
    email_template_name = 'accounts/mail_template/reset/message.txt'
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    success_url = reverse_lazy('password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'accounts/password_reset_complete.html'

templates/accounts/password_change.html
{% extends "base.html" %}

{% block title %}パスワード変更{% endblock %}

{% block content %}
<div id="main">
    <div class="row justify-content-md-center">
        <section>
            <div  class="col-6">
                <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        <label class="col-6" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% csrf_token %}
                    <div class="form-group row">
                      <div class="col-sm">
                        <button type="submit" class="btn btn-primary btn-block">送信</button>
                      </div>
                      <div class="col-sm">
                        <button type="submit" class="btn btn-primary btn-block" onClick="javascript:history.go(-1);">戻る</button>
                      </div>
                    </div>
                </form>
            </div>
        </section>
    </div>
</div>
{% endblock %}

templates/accounts/password_change_done.html
{% extends "base.html" %}

{% block title %}パスワード変更完了{% endblock %}

{% block content %}
<div id="main">
  <section>
    <div class="row justify-content-md-center">
      <div  class="col-4">
        <p>パスワードを変更しました。</p>
        <div class="form-group row">
          <div class="col-6">
            <a class="btn btn-primary btn-block" href="{% url 'top' %}">トップへ</a>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
<div id="main">
    <section>
        <form action="" method="POST">
        <p>
            パスワード再設定を完了しました。<br>
            <a class="btn btn-primary btn-block" href="{% url 'top' %}">ログイン</a>
        </p>
        </form>
    </section>
</div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div id="main">
    <section>
        <form action="" method="POST">
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-block">送信</button>
        </form>
    </section>
</div>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block title %}
  パスワードリセット（メール送信）
{% endblock %}

{% block content %}
<div id="main">
    <section>
      <form action="" method="POST">
        <p>パスワードリセットのメールを送信しました。
          <br/>
          メールに記載されているリンクからパスワードの再設定を行ってください。
          <br/>
          <br/>
          <br/>
          <a class="btn btn-primary col-4" href="{% url 'top' %}">ログイン画面へ</a>
        </p>
      </form>
    </section>
</div>
{% endblock %}

templates/accounts/password_reset_form.html
{% extends "base.html" %}

{% block title %}password reset{% endblock %}

{% block content %}
<div id="main">
    <section>
        <form action="" method="POST">
            {{ form.non_field_errors }}
            <p>メールを受信してパスワードの変更手続きを行います。</p>
            <p>メールアドレスを入力して送信ボタンを押してください。</p>
            <br>
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            {% csrf_token %}

            <p>メールアドレスはあらかじめシステムに登録が必要です。</p>
            <p>メールが届かない場合はシステム管理者に連絡してください。</p>
            <br/>
            <div class="form-group row">
              <div class="col-6">
                <button type="submit" class="btn btn-primary btn-block">送信</button>
              </div>
            </div>
        </form>
    </section>
</div>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}

{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
<div id="main">
    <section id="new-register-section">
        <h2 style="display: none;">新規登録</h2>
        <form action="" method="POST">
            {{ form.non_field_errors }}
            <div class="form-group">
                <label for="id_email">メールアドレス</label>
                <input type="email" name="email" placeholder="email" maxlength="254" class="form-control" required id="id_email">
                {{ form.email.errors }}
            </div>
            <div class="form-group">
                <label for="id_password1">パスワード</label>
                <input type="password" placeholder="Password" name="password1" class="form-control" required id="id_password1">
                {{ form.password1.errors }}
            </div>
            <div class="form-group">
                <label for="id_password2">パスワード(確認用)</label>
                <input type="password" placeholder="Password" name="password2" class="form-control" required id="id_password2">
                {{ form.password2.errors }}
            </div>
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-lg">送信</button>
            </form>
    </section>
    <a href="{% url 'quizzes:top' %}">Homeに戻る</a>
</div>
{% endblock %}

templates/accounts/user_create_complete.html
{% extends "base.html" %}
{% block content %}
<div id="main">
    <p>
        本登録が完了しました。<br>
        登録されたメールアドレスとパスワードでログインしてください。<br>
        <a class="btn btn-primary btn-lg" href="{% url 'login' %}">ログイン</a>
    </p>
</div>
{% endblock %}

templates/accounts/user_create_done.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<div id="main">
    <p>
        会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
        確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
    </p>
</div>
{% endblock %}